#!/usr/bin/env bash
# Bash script must accept 2 arguments: domain, subdomain.

info_all ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];
    then
	info_all "$1" "$subdomain"
    fi
done
