#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
