#!/usr/bin/env bash
# Bash script that loops from 1 to 10

i=0
while [ $i -lt 11 ]
do
	if [ $i = 4 ]
	then
	    echo "bad luck"
	elif [ $i = 8 ]
	then
	    echo "good luck"
	else
       	    echo "Holberton School"
	fi
	(( i+=1 ))
done
