#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 69 minutes

i=1
while [ $i -lt 13 ]
do
	echo "Hour: $i"
	j=1
	while [ $j -lt 60 ]
	do
		echo $j
		(( j+=1 ))
	done
	(( i+=1 ))
done
